username = input ("Введите ваше имя: ")
title = input ("Введите заголовок: ")
content = input("Введите содержание заметки: ")
status = input ("Введите статус заметки: ")
created_date = input ("Введите дату создания (в формате ДД.ММ.ГГГГ): ")
issue_date = input ("Введите дату окончания (в формате ДД.ММ.ГГГГ): ")
print("Имя пользователя:", username)
print("Заголовок:", title)
print("Содержание:", content)
print("Статус:", status)
print("Дата создания:", created_date)
print("Дата окончания:", issue_date)